import type {
  ArticleFrontmatter,
  EditorialMetrics,
  EditorialSource,
  EditorialType,
  ReviewStatus,
} from "./types";

const agenticSignals = [
  "agentic",
  "dashboard",
  "status",
  "system-health",
  "system health",
  "reporte",
  "report",
  "informe gcp",
  "diario automatico",
  "diario-automatico",
  "gcp-ai-microservices-report",
  "system-health-status",
  "dashboard_status",
  "dashboard status",
  "reporte-matutino",
  "generado automáticamente",
  "generated automatically",
];

const humanSignals = ["guia", "guide", "experiencia", "tutorial", "reflexion", "case", "building"];
const validSources = ["human", "agentic", "hybrid"] as const;
const validTypes = ["article", "note", "case-study", "agentic-status", "changelog", "experiment"] as const;
const validReviewStatuses = ["draft", "reviewed", "published"] as const;
const tagPriority = [
  "AI Engineering",
  "Agents",
  "RAG",
  "Backend",
  "Cloud",
  "GCP",
  "Go",
  "Python",
  "TypeScript",
  "MCP",
  "DevOps",
  "System",
  "Monitor",
] as const;
const operationalMetricKeys = [
  "commits",
  "filesChanged",
  "insertions",
  "deletions",
  "postsUpdated",
  "buildStatus",
  "lighthousePerformance",
  "lighthouseAccessibility",
  "lighthouseBestPractices",
  "lighthouseSEO",
  "wordCount",
  "videosEmbedded",
  "internalLinks",
  "externalLinks",
] as const;

export const editorialLabels = {
  es: {
    human: "Humano",
    agentic: "Agentic",
    hybrid: "Híbrido",
    reviewed: "Revisado",
    published: "Publicado",
    draft: "Borrador",
    agenticSection: "Reportes agenticos",
    agenticIntro:
      "Estados, reportes y cambios generados por flujos técnicos. Se separan del ensayo humano y solo muestran métricas disponibles.",
    humanSection: "Artículos editoriales",
    noVerifiedMetrics: "Sin métricas operacionales verificables en metadata.",
  },
  en: {
    human: "Human",
    agentic: "Agentic",
    hybrid: "Hybrid",
    reviewed: "Reviewed",
    published: "Published",
    draft: "Draft",
    agenticSection: "Agentic reports",
    agenticIntro:
      "Status notes, reports and changes generated by technical workflows. They stay separate from human essays and only show available metrics.",
    humanSection: "Editorial articles",
    noVerifiedMetrics: "No verifiable operational metrics in metadata.",
  },
} as const;

const toSearchText = (entry: Partial<ArticleFrontmatter>) =>
  [
    entry.filename,
    entry.title,
    entry.description,
    entry.category,
    ...(entry.tags ?? []),
    entry.origin?.generatedBy,
    entry.origin?.agentName,
    entry.origin?.workflow,
  ]
    .filter(Boolean)
    .join(" ")
    .toLowerCase();

const isValidDate = (value?: string) => Boolean(value && !Number.isNaN(new Date(value).getTime()));

export function dateFromPath(value?: string) {
  const match = value?.match(/(20\d{2})[-_](\d{2})[-_](\d{2})/);
  if (!match) return undefined;
  return `${match[1]}-${match[2]}-${match[3]}T00:00:00-04:00`;
}

export function inferSource(entry: Partial<ArticleFrontmatter>): EditorialSource {
  if (entry.source && validSources.includes(entry.source)) return entry.source;
  const text = toSearchText(entry);
  if (agenticSignals.some((signal) => text.includes(signal))) return "agentic";
  if (humanSignals.some((signal) => text.includes(signal))) return "human";
  return "human";
}

export function inferType(entry: Partial<ArticleFrontmatter>): EditorialType {
  if (entry.type && validTypes.includes(entry.type)) return entry.type;
  const text = toSearchText(entry);
  if (text.includes("changelog")) return "changelog";
  if (text.includes("experiment") || text.includes("experimento")) return "experiment";
  if (text.includes("status") || text.includes("health") || text.includes("dashboard")) return "agentic-status";
  if (text.includes("case-study") || text.includes("case study")) return "case-study";
  if (inferSource(entry) === "agentic") return "agentic-status";
  return "article";
}

export function inferLang(entry: Partial<ArticleFrontmatter>): "es" | "en" {
  if (entry.lang === "en" || entry.lang === "es") return entry.lang;
  const text = `${entry.filename ?? ""} ${entry.title ?? ""}`.toLowerCase();
  if (text.endsWith("-en") || text.includes("-story-en") || /(^|\s)(what|how|why|building|future)\b/.test(text)) return "en";
  return "es";
}

export function inferReviewStatus(entry: Partial<ArticleFrontmatter>): ReviewStatus {
  if (entry.reviewStatus && validReviewStatuses.includes(entry.reviewStatus)) return entry.reviewStatus;
  if (entry.draft === true) return "draft";
  return inferSource(entry) === "agentic" ? "reviewed" : "published";
}

export function normalizeMetrics(entry: Partial<ArticleFrontmatter>): EditorialMetrics | undefined {
  const metrics = { ...(entry.metrics ?? {}) };
  if (typeof entry.time === "number" && metrics.readingTime === undefined) {
    metrics.readingTime = entry.time;
  }
  return Object.keys(metrics).length > 0 ? metrics : undefined;
}

export function normalizeTags(tags?: string[]) {
  if (!tags) return undefined;
  const unique = [...new Set(tags.map((tag) => tag.trim()).filter(Boolean))];
  return unique.sort((a, b) => {
    const aIndex = tagPriority.findIndex((tag) => tag.toLowerCase() === a.toLowerCase());
    const bIndex = tagPriority.findIndex((tag) => tag.toLowerCase() === b.toLowerCase());
    if (aIndex === -1 && bIndex === -1) return a.localeCompare(b);
    if (aIndex === -1) return 1;
    if (bIndex === -1) return -1;
    return aIndex - bIndex;
  });
}

export function normalizeEditorial(entry: ArticleFrontmatter): ArticleFrontmatter {
  const timestamp = isValidDate(entry.timestamp) ? entry.timestamp : dateFromPath(entry.filename) ?? entry.timestamp;
  const pubDate = entry.pubDate ?? entry.publishDate ?? timestamp;
  return {
    ...entry,
    timestamp,
    tags: normalizeTags(entry.tags),
    pubDate,
    updatedDate: entry.updatedDate ?? entry.modifiedDate ?? pubDate,
    lang: inferLang(entry),
    type: inferType(entry),
    source: inferSource(entry),
    author: entry.author ?? "Jaime Hernández",
    authorHandle: entry.authorHandle ?? "devjaime",
    reviewStatus: inferReviewStatus(entry),
    metrics: normalizeMetrics(entry),
  };
}

export function isEditorialArticle(entry: ArticleFrontmatter) {
  return entry.source !== "agentic";
}

export function isAgenticEntry(entry: ArticleFrontmatter) {
  return entry.source === "agentic";
}

export function formatEditorialSource(source: EditorialSource | undefined, lang: "es" | "en") {
  if (!source) return editorialLabels[lang].human;
  return editorialLabels[lang][source];
}

export function hasOperationalMetrics(metrics?: EditorialMetrics) {
  if (!metrics) return false;
  return operationalMetricKeys.some((key) => metrics[key] !== undefined && metrics[key] !== null && metrics[key] !== "");
}

export function visibleOperationalMetrics(metrics?: EditorialMetrics) {
  if (!metrics) return [];
  return operationalMetricKeys
    .filter((key) => metrics[key] !== undefined && metrics[key] !== null && metrics[key] !== "")
    .map((key) => [key, metrics[key]] as const);
}
